Vagrant.configure("2") do |config|
  config.vm.define "vagrant1" do |vagrant1|
    vagrant1.vm.box = "ubuntu/xenial64"
    vagrant1.vm.network "forwarded_port", guest: 80, host: 8080
    vagrant1.vm.network "forwarded_port", guest: 443, host: 8443
    vagrant1.vm.network "private_network", type: "dhcp"

  end

  config.vm.define "vagrant2" do |vagrant2| 
    vagrant2.vm.box = "ubuntu/xenial64"
    vagrant2.vm.network "private_network", type: "dhcp"
  end
  config.vm.define "vagrant3" do |vagrant3| 
    vagrant3.vm.box = "ubuntu/xenial64"
    vagrant3.vm.network "private_network", type: "dhcp"
  end
end
